x-spark-common: &spark-common
  image: bitnami/spark-extended:latest
  networks:
    - spark-network

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      # - ./config/spark-defaults.conf:/obt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - "8080:8080"
      - "8888:7077"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
  
  spark-woker:
    <<: *spark-common
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    depends_on:
      spark-master:
        condition: service_healthy

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"  # MinIO API
      - "9090:9090"  # MinIO Web UI
    networks:
      - spark-network
    volumes:
      - minio_data:/data

networks:
  spark-network:
    driver: bridge

volumes:
  minio_data: